import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Fatemeh Alavi | Personal Portfolio",
  description: "Generated by create next app , Student Front end developer",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="ltr">
      <body className=" max-w-screen-sm mx-auto bg-[#FFF8E8] ">{children}</body>
    </html>
  );
}
